### PR TITLE
Update Tailor (v2.3.0)

### PR DESCRIPTION
**Pull request by danielbayerlein**
* Update `node-tailor` to v`2.3.0`
* Update `standard` to v`10.0.2`

### CODE REVIEW

**Comment by danielbayerlein** [comment]
@chrishelgert Can you publish `hapi-tailor-middleware` version `1.2.0` on npm, please?

**Comment by chrishelgert** [comment]
is in work 👍

**Comment by chrishelgert** [comment]
@danielbayerlein should be done
https://github.com/chrishelgert/hapi-tailor-middleware/releases/tag/v1.2.0

**Comment by danielbayerlein** [comment]
Thank you!

**Pull request merged**
